name: summa-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8.8
  - pip
  - pathlib
  - numpy
  - xarray
  - netCDF4
  - gdal
  - pandas
  - geopandas
  - sphinx
  - pip:
    - easymore
    - sphinx-rtd-theme
